name: timedistill
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2024.7.2
  - cudatoolkit=11.0.221
  - intel-openmp=2021.4.0
  - libedit=3.1.20230828
  - libffi=3.2.1
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuv=1.48.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - openssl=1.1.1w
  - pip=24.0
  - python=3.8.0
  - readline=7.0
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.33.0
  - tk=8.6.14
  - typing_extensions=4.11.0
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - absl-py==2.1.0
    - ace-tools==0.0
    - asttokens==2.4.1
    - axial-positional-embedding==0.2.1
    - backcall==0.2.0
    - cachetools==5.4.0
    - certifi==2024.7.4
    - charset-normalizer==3.3.2
    - contourpy==1.1.1
    - cycler==0.12.1
    - deprecated==1.2.14
    - docopt==0.6.2
    - einops==0.5.0
    - executing==2.1.0
    - fonttools==4.53.1
    - google-auth==2.32.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.65.1
    - idna==3.7
    - importlib-metadata==8.0.0
    - importlib-resources==6.4.0
    - ipdb==0.13.13
    - ipython==8.12.3
    - jedi==0.19.1
    - joblib==1.4.2
    - kiwisolver==1.4.5
    - llvmlite==0.41.1
    - local-attention==1.4.4
    - markdown==3.6
    - markupsafe==2.1.5
    - matplotlib==3.7.0
    - matplotlib-inline==0.1.7
    - mpmath==1.3.0
    - numba==0.58.1
    - numpy==1.23.5
    - oauthlib==3.2.2
    - packaging==24.1
    - pandas==1.5.3
    - parso==0.8.4
    - patool==1.12
    - pickleshare==0.7.5
    - pillow==10.4.0
    - pipreqs==0.4.13
    - prettytable==3.10.2
    - product-key-memory==0.1.10
    - prompt-toolkit==3.0.47
    - protobuf==5.27.2
    - psutil==6.0.0
    - pure-eval==0.2.3
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - reformer-pytorch==1.4.4
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rsa==4.9
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.13.2
    - sktime==0.16.1
    - stack-data==0.6.3
    - sympy==1.11.1
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - thop==0.1.1-2209072238
    - threadpoolctl==3.5.0
    - torch==1.10.1
    - tqdm==4.64.1
    - traitlets==5.14.3
    - urllib3==2.2.2
    - wcwidth==0.2.13
    - werkzeug==3.0.3
    - wrapt==1.16.0
    - yarg==0.1.10
    - zipp==3.19.2
